name: Generator
on:
  push:
    branches:    
      - main
jobs:
  sync-to-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      
      - name: JSON Resume Convert
        uses: rvdwegen/action-jsonresume-convert@latest
        with:
          # JSONResume theme name. Assumes the theme package would be found as `jsonresume-theme-{theme}` in NPM.
          theme: stackoverflow
          resume_filepath: resume.json
          output_html_filepath: docs/index.html
          output_pdf_filepath: docs/resume.pdf
  
      - name: Deploy resume.json
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GHA_TOKEN_FOR_GISTS }}
          gist_id: bdfc617628bc7a2fc8763a2be6b1a816
          file_path: resume.json
          file_type: binary

      - name: Deploy resume.pdf
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GHA_TOKEN_FOR_GISTS }}
          gist_id: bdfc617628bc7a2fc8763a2be6b1a816
          file_path: docs/resume.pdf
          file_type: binary
      
      - name: Commit published HTML
        id: commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/index.html
          git add docs/resume.pdf
          git commit -m "Added generated file changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GHA_TOKEN_FOR_PUSH }}
          branch: generated-page
