name: Generator
on: [push]
jobs:
  sync-to-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: JSON Resume Convert
        uses: rvdwegen/action-jsonresume-convert@latest
        with:
          # JSONResume theme name. Assumes the theme package would be found as `jsonresume-theme-{theme}` in NPM.
          theme: stackoverflow
          resume_filepath: resume.json
          output_html_filepath: resume.html
          output_pdf_filepath: resume.pdf
  
      - name: Deploy resume.json
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GHA_TOKEN_FOR_GISTS }}
          gist_id: bdfc617628bc7a2fc8763a2be6b1a816
          file_path: resume.json
          file_type: binary

      - name: Deploy resume.pdf
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GHA_TOKEN_FOR_GISTS }}
          gist_id: bdfc617628bc7a2fc8763a2be6b1a816
          file_path: resume.pdf
          file_type: binary

      - name: Deploy resume.html
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GHA_TOKEN_FOR_GISTS }}
          gist_id: bdfc617628bc7a2fc8763a2be6b1a816
          file_path: resume.html
          file_type: binary
