name: GitHub Actions Demo
on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: JSON Resume Convert
        # You may pin to the exact commit or the version.
        # uses: rvdwegen/action-jsonresume-convert@1a3bfb03c607b72281a44b481c74ac41bf0e2c35
        uses: rvdwegen/action-jsonresume-convert@latest
        with:
          # JSONResume theme name.
      # Assumes the theme package would be found 
      # as `jsonresume-theme-{theme}` in NPM.
      # You can search for themes at https://npmsearch.com/?q=jsonresume-theme
          theme: jsonresume-theme-stackoverflow
          # File path of the resume in JSONResume format

          resume_filepath: resume.json
          # Output file path for exported HTML file.

          output_html_filepath: index.html
          # Output file path for exported PDF file.

          output_pdf_filepath: resume.pdf
